name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted  # Ensure self-hosted runner is configured

    strategy:
      matrix:
        node-version: [22.x]  # Change to LTS version of Node.js (recommend Node 20.x)

    steps:
    - uses: actions/checkout@v4  # Checkout the code from the repository
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Cache npm dependencies

    - name: Install Dependencies
      run: npm ci  # Clean install dependencies

    - name: Build the Project (Optional)
      run: npm run build --if-present  # Build if there's a build script
    
    - name: Install Serverless Framework
      run: npm install -g serverless  # Install Serverless globally

    - name: Deploy with Serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        serverless deploy --stage production  # Deploy using the serverless framework
