name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Ensure self-hosted runner is configured

    strategy:
      matrix:
        node-version: [22.x]  # Use LTS version of Node.js

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Checkout the repository

      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Cache npm dependencies for faster builds

      - name: Install Dependencies
        run: npm ci  # Clean install dependencies

      - name: Build the Project (Optional)
        run: npm run build --if-present  # Build only if a build script exists

      - name: Install Serverless Framework
        run: npm install -g serverless@4  # Install latest Serverless framework

      - name: Deploy with Serverless
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}  # Serverless auth key
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          serverless deploy --stage production  # Deploy using serverless framework
          
